### PR TITLE
Config generate for gcloud

### PR DESCRIPTION
**Pull request by dineshba**
Generate the `config yaml` file using the `gcloud logged-in` account.

Tasks:
- [x] Generate config.yaml file
- [x] Ask confirmation for each project
- [x] Use template for envs
- [x] Use one command instead generating config.yaml file

Currently,
```bash
./out/kube-tmuxp gcloud-generate
```
will generate the config file(or directly tmuxp files) for all projects (all clusters) which user have access to.

### CODE REVIEW

**Comment by jskswamy** [comment]
@dineshba thanks for this feature.

Kindly add add examples in README.md:
- on how to use this feature
- how to pass additional parameters

I'm also thinking whether:
- we should move the command `gcloud-generate` under `generate` command?
- or the only use case of this tool is to generate kube-tumxp, hence can we have separate sub command for every cloud provider?

I'm open for discussion, lets think for better UX for tool to accommodate other cloud provider

Once we agree on the UX and made necessary changes, we can merge it to master and release new version of this tool

**Comment by jskswamy** [comment]
@aswinkarthik @arunvelsriram let me know your thoughts

**Comment by dineshba** [comment]
Updated Readme @jskswamy... May be having subcommands is okay for now. If we introduce another provider, we can see how to merge. I am okay with flags also. Both looks good to me. No concerns.

@aswinkarthik @arunvelsriram provide you thoughts also.

**Comment by arunvelsriram** [comment]
1. Like @jskswamy said the only use case of this tool is to generate configs so I prefer passing the provider as argument.

* to generate kube-tmuxp config from gcloud: `kube-tmuxp config --from gcloud`
* to generate tmuxp config using kube-tmuxp configuration: `kube-tmuxp generate`

2. We should follow default unix convention for the flags. Like `--all-projects` instead of `--allProjects`

3. When `config.yaml` already exists what will be the behavior of `gcloud-generate`?

**Comment by dineshba** [comment]
1) For Point 2 I will make changes to the PR.
2) Do we need to generate config file for gcloud ? Can we directly get kubeconfigs and generate tmuxp files ?
I am okay with directly creating (may be we can give dry-run which will generate the kube-tmuxp config file).
So UX that I am suggesting
```bash
$ kube-tmuxp gen --from file.yaml
$ kube-tmuxp gen --from gcloud # this can take projectID flags
$ kube-tmuxp gen --from digitalocean
```

**Comment by jskswamy** [comment]
@dineshba are we expecting any other command other than generate? If not we completely avoid the subcommand `gen`

```
$ kube-tmuxp --from file.yaml
$ kube-tmuxp --from gcloud # this can take projectID flags
$ kube-tmuxp --from digitalocean
```

I'm also thinking we should support to import the existing configs from ~/.kube/configs and generate tmuxp files

**Comment by dineshba** [comment]
> I'm also thinking we should support to import the existing configs from ~/.kube/configs and generate tmuxp files

You mean splitting the `~./kube/config` file into multiple files under directory `~/.kube/configs/` ?

With `gen or generate` subcommand it looks very odd to me

**Comment by jskswamy** [comment]
If a user has already has multiple kube configs under `~/.kube/configs/` we could simply go through the configs and generate `~/.tmuxp/*.yaml` files

```
$ kube-tmuxp generate --from file.yaml
$ kube-tmuxp generate --from gcloud # this can take projectID flags
$ kube-tmuxp generate --from digitalocean
```

```
# command will import existing `~/.kube/configs` and generate `~/.tmuxp/*.yaml`
$ kube-tmuxp import
```

**Comment by dineshba** [comment]
I feel chances of having `~/.kube/configs/` folder is very less. 
Most people will have all config in one file `~/.kube/config`. May be we can also give a subcommand which can split all configs and put in `~/.kube/configs` directory and generate `~/.tmuxp/*.yaml`

**Comment by jskswamy** [comment]
@dineshba I agree, then I don't see an need for subcommand, how about the following UX

```
$ kube-tmuxp --from file.yaml
$ kube-tmuxp --from gcloud # this can take projectID flags
$ kube-tmuxp --from digitalocean
$ kube-tmuxp --from local # We can make this as default
```

**Comment by arunvelsriram** [comment]
> Do we need to generate config file for gcloud ? Can we directly get kubeconfigs and generate tmuxp files ?

Yes we can directly generate too. However how we will config that can be shared with all team members. For example, injecting custom extra env vars inside sessions.

**Comment by dineshba** [comment]
Hi @arunvelsriram 
Does this help 
```bash
kube-tmuxp gcloud-generate --additionalEnvs 'NEW_KEY=new_value,NEW_ENV=$HOME,KUBE_CONFIG=$HOME/.kube/configs/$KUBETMUXP_CLUSTER_NAME'
```
We can share the command (which can inject the additionalEnvs) instead of files.

Or I am perfectly okay with having `--output` which will output the `kube-tmuxp-config` file which can be shared and others can apply using `kube-tmuxp --from file`

**Comment by arunvelsriram** [comment]
@dineshba lets go with whichever is simplest.

**Comment by dineshba** [comment]
kube-tmuxp will have the same commands are before in order to provide backward compatibility (generate,version,help)

```sh
$ kube-tmuxp generate --help
Generates tmuxp configs for various Kubernetes contexts

Usage:
  kube-tmuxp generate [flags]

Aliases:
  generate, gen

Flags:
      --additional-envs strings   Additional envs to be populated
      --all-projects              Skip confirmation for projects
      --apply                     Directly create the tmuxp configs for selected projects
      --from string               source from which the tmuxp config files are  generated (default "file")
  -h, --help                      help for generate
      --project-ids strings       Comma separated Project IDs to which the configurations need to be fetched

Global Flags:
      --config string   config file (default "/Users/dinesh/kube-tmuxp.yaml")
```

Valid commands:
```sh
$ kube-tmuxp generate  # will look for config file in default location
$ kube-tmuxp generate --from file # will look for config file in default location
$ kube-tmuxp generate --from file --config /location/file.yaml # will look for config file provided
$ kube-tmuxp generate --from gcloud # will fetch all gcloud projects for the current logged in user
```
If `--from file`, then additional-envs,all-projects,project-ids flags are not valid
If `--from gcloud`, then config flag is invalid.

Let me know your inputs

**Comment by dineshba** [comment]
@jskswamy @arunvelsriram @aswinkarthik Any update on this ?

**Comment by jskswamy** [comment]
@dineshba looks good to me, maybe we can add support for additional environment variables from file using another flag `--additional-envs-file`

**Comment by dineshba** [comment]
May be in another PR @jskswamy ... This PR is waiting for long time :-|

**Comment by jskswamy** [comment]
@dineshba I'm testing it locally @dineshba on the UX, if it looks good I'll go ahead and merge this

**Comment by dineshba** [comment]
Okay cool 👍🏽

**Comment by jskswamy** [comment]
@dineshba looks good to me, merging this

**Pull request merged**
